parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    BackendBundle\Repository\:
        resource: '../../Repository'

    BackendBundle\Controller\:
        resource: '../../Controller'

    BackendBundle\Decorators\:
        resource: '../../Decorators'

    BackendBundle\Services\:
        resource: '../../Services'

    BackendBundle\Security\:
        resource: '../../Security'


    # Services

    BackendBundle\Security\FormLoginAuthenticator:
        arguments:
            $path: ''
# GEDMO

