# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    login_check_path: /signin_check

#    parameter_name: value

services:
