# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    login_check_path: /signin_check

#    parameter_name: value

services:
    app.form_login_authenticator:
        class: LearnHub\WebApp\WebAppBundle\Security\FormLoginAuthenticator
        arguments: ["@router", "@security.password_encoder", "%login_check_path%",'@request_stack']
    app.translation.loader.db:
        class: LearnHub\MainApp\MainAppBundle\Services\DBLoader
        arguments: ['@doctrine.orm.default_entity_manager']
        tags:
            - { name: translation.loader, alias:db}
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
